# Generated by Django 6.1.1 on 2026-09-29 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0007_remove_chat_message_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatThreadDeletion',
            fields=[
                ('thread_id', models.UUIDField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
