# Generated by Django 6.1.1 on 2026-09-29 05:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0008_chat_thread_deletion_outbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatthreaddeletion',
            name='token',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
